@startuml class-diagram
  skinparam svgLinkTarget _blank
  skinparam topurl https://github.com/RADJOU-Dinesh-24003262/SAEManager/tree/dev/App/src
  package Views as Views {
    package Index as Views.Index {
      class "IndexView\n<b>Class IndexView</b>" as Views_Index_IndexView [[/Views/Index/IndexView.php IndexView Class]] {
        #templatePath()
        #templateKeys()
        -renderErrorMessages(errors)
        -renderSuccessMessage(success)
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
      }
    }
    package SaeSujet as Views.SaeSujet {
      class "SaeSujetView\n<b>Class SaeSujetView</b>" as Views_SaeSujet_SaeSujetView [[/Views/SaeSujet/SaeSujetView.php SaeSujetView Class]] {
        #templatePath()
        #templateKeys()
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
      }
    }
    package Settings as Views.Settings {
      class "EditProfileView\n<b>Edit Profile View</b>" as Views_Settings_EditProfileView [[/Views/Settings/EditProfileView.php EditProfileView Class]] {
        #templatePath()
        #templateKeys()
        #getNameCss()
      }
      class "EditProfileSuccessView\n<b>Edit Profile Success View</b>" as Views_Settings_EditProfileSuccessView [[/Views/Settings/EditProfileSuccessView.php EditProfileSuccessView Class]] {
        #templatePath()
        #templateKeys()
        #getNameCss()
      }
      class "SettingsView\n<b>Class SettingsView</b>" as Views_Settings_SettingsView [[/Views/Settings/SettingsView.php SettingsView Class]] {
        +__construct(data)
        #templatePath()
        #templateKeys()
        -getUserTypeLabel(user)
        #getNameCss()
      }
      class "DeleteUserView\n<b>Class DeleteUserView</b>" as Views_Settings_DeleteUserView [[/Views/Settings/DeleteUserView.php DeleteUserView Class]] {
        +templatePath()
        +templateKeys()
        +getNameCss()
      }
    }
    package User as Views.User {
      class "RegisterSuccessView\n<b>Class RegisterSuccessView</b>" as Views_User_RegisterSuccessView [[/Views/User/RegisterSuccessView.php RegisterSuccessView Class]] {
        -user : User
        +__construct(user)
        #templatePath()
        #templateKeys()
        -getUserTypeLabel()
        -getAcademicInfo()
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
      }
      class "LoginView\n<b>Class LoginView</b>" as Views_User_LoginView [[/Views/User/LoginView.php LoginView Class]] {
        #templatePath()
        #templateKeys()
        -renderErrorMessages(errors)
        #getNameCss()
        #getAdditionalHeaders()
      }
      class "RegisterView\n<b>Class RegisterView</b>" as Views_User_RegisterView [[/Views/User/RegisterView.php RegisterView Class]] {
        #templatePath()
        #templateKeys()
        -renderErrorMessages(errors)
        #getPageTitle()
        #getAdditionalScripts()
        #getNameCss()
        #getAdditionalHeaders()
      }
    }
    package Info as Views.Info {
      class "SiteMapView\n<b>Class SiteMapView</b>" as Views_Info_SiteMapView [[/Views/Info/SiteMapView.php SiteMapView Class]] {
        #templatePath()
        #templateKeys()
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
      }
      class "LegalNoticeView\n<b>Class LegalNoticeView</b>" as Views_Info_LegalNoticeView [[/Views/Info/LegalNoticeView.php LegalNoticeView Class]] {
        #templatePath()
        #templateKeys()
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
      }
    }
    package Dashboard as Views.Dashboard {
      class "DashboardView\n<b>Class DashboardView</b>" as Views_Dashboard_DashboardView [[/Views/Dashboard/DashboardView.php DashboardView Class]] {
        +__construct(data)
        #templatePath()
        #templateKeys()
        -renderErrorMessages(errors)
        -renderSuccessMessage()
        -getUserTypeLabel(user)
        -renderUserMetaInfo(user)
        -renderSAENavigation(user)
        -renderSAEContent(user, saes)
        -renderSAECard(user, sae)
        -renderEmptyState(user)
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
      }
    }
    package PageSAE as Views.PageSAE {
      class "PageSaeView\n<b>Class PageSaeView</b>" as Views_PageSAE_PageSaeView [[/Views/PageSAE/PageSaeView.php PageSaeView Class]] {
        #templatePath()
        #templateKeys()
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
      }
    }
    package pwd as Views.pwd {
      class "ResetPasswordView\n<b>Class ResetPasswordView</b>" as Views_pwd_ResetPasswordView [[/Views/pwd/ResetPasswordView.php ResetPasswordView Class]] {
        +__construct(token, email)
        #templatePath()
        #templateKeys()
        -maskEmail(email)
        -renderErrorMessages(errors)
        #getPageTitle()
        #getNameCss()
        #getAdditionalScripts()
        #getAdditionalHeaders()
      }
      class "ResetPasswordSuccessView\n<b>Class ResetPasswordSuccessView</b>" as Views_pwd_ResetPasswordSuccessView [[/Views/pwd/ResetPasswordSuccessView.php ResetPasswordSuccessView Class]] {
        #templatePath()
        #templateKeys()
        #getPageTitle()
        #getNameCss()
        #getAdditionalScripts()
        #getAdditionalHeaders()
      }
      class "ForgotPasswordView\n<b>Class ForgotPasswordView</b>" as Views_pwd_ForgotPasswordView [[/Views/pwd/ForgotPasswordView.php ForgotPasswordView Class]] {
        #templatePath()
        #templateKeys()
        -renderErrorMessages(errors)
        -renderSuccessMessage(success)
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
      }
    }
    package ToDoList as Views.ToDoList {
      class "ToDoListView\n<b>Class ToDoListView</b>" as Views_ToDoList_ToDoListView [[/Views/ToDoList/ToDoListView.php ToDoListView Class]] {
        #templatePath()
        #templateKeys()
        -renderErrorMessages(errors)
        #getPageTitle()
        #getNameCss()
        #getAdditionalHeaders()
        #getAdditionalScripts()
      }
    }
  }
  package Models as Models {
    package SAE as Models.SAE {
      class "SAE\n<b>Represents a SAE (Situations d'Apprentissage et d'Évaluation) subject in the system.</b>" as Models_SAE_SAE [[/Models/SAE/SAE.php SAE Class]] {
        -sae_subject_id : integer
        -responsible_prof_id : integer
        -client_id : integer
        -subject_name : string
        -begin_date : string
        -end_date : string
        #__construct(data)
        {static} +createSAEsFromArray(saes)
        +getDataArray()
        +getSaeSubjectId()
        +setSaeSubjectId(sae_subject_id)
        +getResponsibleProfId()
        +setResponsibleProfId(responsible_prof_id)
        +getClientId()
        +setClientId(client_id)
        +getSubjectName()
        +setSubjectName(subject_name)
        +getBeginDate()
        +setBeginDate(begin_date)
        +getEndDate()
        +setEndDate(end_date)
      }
    }
    package User as Models.User {
      class "UserRepository\n<b>Class UserRepository</b>" as Models_User_UserRepository [[/Models/User/UserRepository.php UserRepository Class]] {
        -db : Database
        +__construct(db)
        +existsByEmail(email)
        +save(user)
      }
      class "Professor\n<b>Represents a professor user in the system.</b>" as Models_User_Professor [[/Models/User/Professor.php Professor Class]] {
        #amu_id : string
        +__construct(data)
        #saveSpecificData(connection, userId)
        #fetchSpecificData(db, email)
        #fetchSAEData(connection, userId)
        #createSAE(connection, clientid, name, begindate, enddate, userId)
        #updateSAE(connection, sae, data)
        #createGroup(connection, saeID)
        #assignedSAE(connection, groupId, student)
        #removeProfFromSae(connection, saeID, profID)
        #addProfToSae(connection, saeID, profID)
        #unassignedSAE(connection, sae, student)
        +getAmuId()
      }
      class "Client\n<b>Represents a client user in the system.</b>" as Models_User_Client [[/Models/User/Client.php Client Class]] {
        #organisation : string
        +__construct(data)
        #saveSpecificData(connection, userId)
        #fetchSpecificData(db, email)
        #fetchSAEData(connection, userId)
        +getOrganisation()
      }
      class "Student\n<b>Represents a student user in the system.</b>" as Models_User_Student [[/Models/User/Student.php Student Class]] {
        #amu_id : string
        #year : integer
        #major : string|null
        #td : string
        #tp : string
        #sae_group_id : integer
        #student_id : integer
        +__construct(data)
        #saveSpecificData(connection, userId)
        #fetchSpecificData(db, email)
        #fetchSAEData(connection, userId)
        #getToDoList(connection)
        #createToDoIt(connection, desc)
        #checkToDoIt(connection, todoId, checked)
        +getAmuId()
        +getYear()
        +getParcours()
        +getTd()
        +getTp()
      }
      class "User\n<b>Abstract base class for all user types.</b>" as Models_User_User [[/Models/User/User.php User Class]] {
        #user_id : integer
        #first_name : string
        #last_name : string
        #user_type : string
        #email : string
        #hashed_password : string
        #phone : string
        #__construct(data)
        {static} +createFromRegistrationData(data)
        {static} +createFromLoginData(data)
        +setPassword(password)
        +save()
        {abstract} #saveSpecificData(connection, userId)
        +fetchData(email)
        {abstract} #fetchSpecificData(db, email)
        {static} +existsByEmail(email)
        {static} +updatePasswordByEmail(email, newPassword)
        {static} +deleteByEmail(email)
        {static} +modifyField(field, value, email)
        {abstract} #fetchSAEData(connection, userId)
        +getSaes()
        +hasAcessToSae(sae_subject_id)
        +getFirstName()
        +getLastName()
        +getFullName()
        +getUserType()
        +getEmail()
        +getPasswordHash()
        +getPhone()
        +isStudent()
        +isProfessor()
        +isClient()
      }
    }
    package ToDoList as Models.ToDoList {
      class "ToDoList\n<b>Class ToDoList</b>" as Models_ToDoList_ToDoList [[/Models/ToDoList/ToDoList.php ToDoList Class]] {
        -groupId : integer
        -sae_subject_id : ?integer
        -todo_id : integer
        -tododesc : string
        -__construct(data)
        {static} +create(data)
        +getTodoId()
        +getTodoDesc()
        +getSaeGroupId()
        +getSaeSubjectId()
        +setSaeGroupId(groupId)
        +setSaeSubjectId(sae_subject_id)
        +setTododesc(tododesc)
        +setTodoId(todo_id)
        +save()
        +fetchDataFromDatabase(sae_group_id)
        {static} +existBySaeGroupId(sae_group_id)
      }
    }
  }
  package Controllers as Controllers {
    package Index as Controllers.Index {
      class "IndexController\n<b>This class controls the Index page.</b>" as Controllers_Index_IndexController [[/Controllers/Index/IndexController.php IndexController Class]] {
        +control()
        {static} +support(path, method)
      }
    }
    package PageSae as Controllers.PageSae {
      class "PageSaeController\n<b>This class controls the SAE page.</b>" as Controllers_PageSae_PageSaeController [[/Controllers/PageSae/PageSaeController.php PageSaeController Class]] {
        +control()
        {static} +support(path, method)
      }
    }
    package SaeSujet as Controllers.SaeSujet {
      class "SaeSujetController\n<b>Controller for the form of the subject of the SAE.</b>" as Controllers_SaeSujet_SaeSujetController [[/Controllers/SaeSujet/SaeSujetController.php SaeSujetController Class]] {
        +control()
        {static} +support(path, method)
      }
    }
    package Settings as Controllers.Settings {
      class "EditProfileController\n<b>Edit Profile Controller</b>" as Controllers_Settings_EditProfileController [[/Controllers/Settings/EditProfileController.php EditProfileController Class]] {
        +control()
        {static} +support(path, method)
      }
      class "EditProfilePost\n<b>Edit Profile Post Controller</b>" as Controllers_Settings_EditProfilePost [[/Controllers/Settings/EditProfilePost.php EditProfilePost Class]] {
        +control()
        {static} +support(path, method)
      }
      class "SettingsController\n<b>Settings Controller</b>" as Controllers_Settings_SettingsController [[/Controllers/Settings/SettingsController.php SettingsController Class]] {
        +control()
        {static} +support(path, method)
      }
      class "DeleteUserController\n<b>DeleteUser Controller</b>" as Controllers_Settings_DeleteUserController [[/Controllers/Settings/DeleteUserController.php DeleteUserController Class]] {
        +control()
        {static} +support(path, method)
      }
    }
    package User as Controllers.User {
      class "Logout\n<b>Logout controller.</b>" as Controllers_User_Logout [[/Controllers/User/Logout.php Logout Class]] {
        +control()
        {static} +support(path, method)
      }
      class "Register\n<b>This class controls the register process (get).</b>" as Controllers_User_Register [[/Controllers/User/Register.php Register Class]] {
        +control()
        {static} +support(path, method)
      }
      class "LoginPost\n<b>This class controls the login process (post).</b>" as Controllers_User_LoginPost [[/Controllers/User/LoginPost.php LoginPost Class]] {
        +control()
        {static} +support(path, method)
      }
      class "Login\n<b>Class Login (GET)</b>" as Controllers_User_Login [[/Controllers/User/Login.php Login Class]] {
        +control()
        {static} +support(path, method)
      }
      class "RegisterPost\n<b>This class controls the register process (post).</b>" as Controllers_User_RegisterPost [[/Controllers/User/RegisterPost.php RegisterPost Class]] {
        +control()
        {static} +support(path, method)
      }
    }
    package Info as Controllers.Info {
      class "SiteMapController\n<b>This class controls the site map page.</b>" as Controllers_Info_SiteMapController [[/Controllers/Info/SiteMapController.php SiteMapController Class]] {
        +control()
        {static} +support(path, method)
      }
      class "LegalNoticeController\n<b>This class controls the legal notice page.</b>" as Controllers_Info_LegalNoticeController [[/Controllers/Info/LegalNoticeController.php LegalNoticeController Class]] {
        +control()
        {static} +support(path, method)
      }
    }
    package Dashboard as Controllers.Dashboard {
      class "DashboardController\n<b>Controller responsible for handling the dashboard page.</b>" as Controllers_Dashboard_DashboardController [[/Controllers/Dashboard/DashboardController.php DashboardController Class]] {
        +control()
        {static} +support(path, method)
      }
    }
    package pwd as Controllers.pwd {
      class "ForgotPasswordPostController\n<b>Handles the POST request to the "/forgot-password" route.</b>" as Controllers_pwd_ForgotPasswordPostController [[/Controllers/pwd/ForgotPasswordPostController.php ForgotPasswordPostController Class]] {
        +control()
        {static} +support(path, method)
      }
      class "ForgotPasswordController\n<b>This class controls the forgot password process (get).</b>" as Controllers_pwd_ForgotPasswordController [[/Controllers/pwd/ForgotPasswordController.php ForgotPasswordController Class]] {
        +control()
        {static} +support(path, method)
      }
      class "ResetPasswordPostController" as Controllers_pwd_ResetPasswordPostController [[/Controllers/pwd/ResetPasswordPostController.php ResetPasswordPostController Class]] {
        +control()
        -renderFormWithToken(token, email)
        {static} +support(path, method)
      }
      class "ResetPasswordController\n<b>This class controls the reset password process (get).</b>" as Controllers_pwd_ResetPasswordController [[/Controllers/pwd/ResetPasswordController.php ResetPasswordController Class]] {
        +control()
        {static} +support(path, method)
      }
    }
    package ToDoList as Controllers.ToDoList {
      class "ToDoListController\n<b>Handles the control logic for the To-Do List page.</b>" as Controllers_ToDoList_ToDoListController [[/Controllers/ToDoList/ToDoListController.php ToDoListController Class]] {
        +control()
        {static} +support(path, method)
      }
      class "ToDoListPost\n<b>This class controls the todolist process (post).</b>" as Controllers_ToDoList_ToDoListPost [[/Controllers/ToDoList/ToDoListPost.php ToDoListPost Class]] {
        +control()
        {static} +support(path, method)
      }
    }
  }
  Controllers_Dashboard_DashboardController ..> Models_User_User
  Controllers_Dashboard_DashboardController ..> Views_Dashboard_DashboardView
  Controllers_Index_IndexController ..> Views_Index_IndexView
  Controllers_Info_LegalNoticeController ..> Views_Info_LegalNoticeView
  Controllers_Info_SiteMapController ..> Views_Info_SiteMapView
  Controllers_PageSae_PageSaeController ..> Models_User_User
  Controllers_PageSae_PageSaeController ..> Views_PageSAE_PageSaeView
  Controllers_SaeSujet_SaeSujetController ..> Views_SaeSujet_SaeSujetView
  Controllers_Settings_DeleteUserController ..> Models_User_User
  Controllers_Settings_DeleteUserController ..> Views_Settings_DeleteUserView
  Controllers_Settings_EditProfileController ..> Views_Settings_EditProfileView
  Controllers_Settings_EditProfilePost ..> Models_User_User
  Controllers_Settings_EditProfilePost ..> Views_Settings_EditProfileSuccessView
  Controllers_Settings_SettingsController ..> Views_Settings_SettingsView
  Controllers_ToDoList_ToDoListController ..> Models_User_User
  Controllers_ToDoList_ToDoListController ..> Views_ToDoList_ToDoListView
  Controllers_ToDoList_ToDoListPost ..> Models_ToDoList_ToDoList
  Controllers_ToDoList_ToDoListPost ..> Views_ToDoList_ToDoListView
  Controllers_User_Login ..> Views_User_LoginView
  Controllers_User_LoginPost ..> Models_User_User
  Controllers_User_LoginPost ..> Views_User_LoginView
  Controllers_User_Logout ..> Views_Index_IndexView
  Controllers_User_Register ..> Views_User_RegisterView
  Controllers_User_RegisterPost ..> Models_User_User
  Controllers_User_RegisterPost ..> Views_User_RegisterSuccessView
  Controllers_User_RegisterPost ..> Views_User_RegisterView
  Controllers_pwd_ForgotPasswordController ..> Views_pwd_ForgotPasswordView
  Controllers_pwd_ForgotPasswordPostController ..> Models_User_User
  Controllers_pwd_ForgotPasswordPostController ..> Views_pwd_ForgotPasswordView
  Controllers_pwd_ResetPasswordController ..> Views_pwd_ResetPasswordView
  Controllers_pwd_ResetPasswordPostController ..> Models_User_User
  Controllers_pwd_ResetPasswordPostController ..> Views_pwd_ResetPasswordSuccessView
  Controllers_pwd_ResetPasswordPostController ..> Views_pwd_ResetPasswordView
  Models_SAE_SAE "1" ..> "*" Models_SAE_SAE
  Models_SAE_SAE ..> Models_SAE_SAE
  Models_User_Professor ..> Models_SAE_SAE
  Models_User_User ..> Models_SAE_SAE
  Models_User_User ..> Models_User_Client
  Models_User_User ..> Models_User_Professor
  Models_User_User ..> Models_User_Student
  Models_User_User ..> Models_User_User
  Models_User_User <|-- Models_User_Client
  Models_User_User <|-- Models_User_Professor
  Models_User_User <|-- Models_User_Student
  Models_User_UserRepository ..> Models_User_User
  Views_Dashboard_DashboardView ..> Models_SAE_SAE
  Views_Dashboard_DashboardView ..> Models_User_Student
  Views_Dashboard_DashboardView ..> Models_User_User
  Views_Settings_SettingsView ..> Models_User_User
  Views_User_RegisterSuccessView ..> Models_User_Student
  Views_User_RegisterSuccessView ..> Models_User_User
@enduml
