<?php

namespace Utilis;

use includes\database;
use includes\exception\ExceptionCreationTokenFailed;
use includes\exception\ExceptionInvalidToken;
use includes\exception\ExceptionSpam;

/**
 * Class TokenService

 * @package     src

 * @subpackage  Utilis

 * @author      Benhafessa Alexandre, Dargentolle Francois, Edelstein William, Griguer Nathan, Radjou Dinesh

 * This class regroups the functions to manage the reset password tokens.
 * It can generate, update, delete and check the validity of the tokkens.
 * Need emails to work.
 */
class TokenService
{
    /**
     * Returns a 64 hexadecimal long random secure string
     *
     * This method creates a 64 character secure random hexadecimal string and returns it
     * @return string
     */
    public static function generate(): string
    {
        return bin2hex(random_bytes(32)); // 64 hexadecimal characters
    }

    /**
     * Creates a password reset token for the given email address.
     *
     * This method performs the following actions:
     * - Deletes existing tokens for the email.
     * - Removes expired tokens from the database.
     * - Generates a new secure token.
     * - Stores the token in the `password_resets` table with a 10-minute expiry.
     *
     * @param string $email The email address to associate with the reset token.
     *
     * @return string The newly generated token as a string.
     *
     * @throws ExceptionCreationTokenFailed If a database error occurs (unless caught internally).
     * @throws ExceptionSpam If too many reset requests are detected for the given email.
     */
    public static function createPasswordResetToken(string $email): string
    {
        try {
            $db = database::getInstance();

            // Clean up old tokens for this email
            self::cleanupExpiredTokens();

            // Generate new token
            $token = self::generate();
            $createdAt = date('Y-m-d H:i:s');
            $expiresAt = date('Y-m-d H:i:s', strtotime('+10 minutes'));

            $stmt = $db->prepare("
                INSERT INTO password_resets (user_email, token, created_at, expires_at, used)
                VALUES (:email, :token, :created_at, :expires_at, FALSE)
            ");

            $stmt->execute([
                'email' => $email,
                'token' => $token,
                'created_at' => $createdAt,
                'expires_at' => $expiresAt
            ]);

            return $token ? $token : throw new ExceptionCreationTokenFailed();
        } catch (\PDOException $e) {
            error_log("Erreur création token: " . $e->getMessage());
            if (strpos($e->getMessage(), 'TOO_MANY_RESET_REQUESTS') !== false) {
                error_log("Trop de demandes de réinitialisation pour: {$email}");
                throw new ExceptionSpam(
                    "Trop de demandes de réinitialisation. "
                    . "Veuillez réessayer plus tard dans quelques minutes."
                );
            } else {
                throw new ExceptionCreationTokenFailed();
            }
        }
    }

    /**
     * Returns the infos about the token given in parameters, false if it fails to or is invalid.
     *
     * This method looks for the token given in parameters and if it exist and is valid, returns it.
     * Exeption relative to the invalidity or non-existence are thrown depending on it's state.
     *
     * @param $token the token to validate.
     *
     * @return string the token of the user, if valid
     *
     * @throws ExceptionInvalidToken if the tokken expired, doesn't exist or is used, throws an exeption.
     */
    public static function validateToken(string $token): array
    {
        try {
            // Sanitize the token: allow only hexadecimal characters (since generated by bin2hex)
            if (!preg_match('/^[a-f0-9]{64}$/i', $token)) {
                throw new ExceptionInvalidToken("Ce lien de réinitialisation est invalide.");
            }

            $db = database::getInstance();

            $stmt = $db->prepare("
                SELECT user_email, expires_at, used 
                FROM password_resets 
                WHERE token = :token
            ");

            $stmt->execute(['token' => $token]);
            $result = $stmt->fetch(\PDO::FETCH_ASSOC);

            if (!$result) {
                throw new ExceptionInvalidToken(
                    "Ce lien de réinitialisation est invalide ou a expiré. "
                    . "Veuillez faire une nouvelle demande."
                );
            }

            if ($result['used']) {
                throw new ExceptionInvalidToken("Ce lien de réinitialisation a déjà été utilisé.");
            }

            if (strtotime($result['expires_at']) < time()) {
                throw new ExceptionInvalidToken("Ce lien de réinitialisation a expiré.");
            }

            return $result;
        } catch (\PDOException $e) {
            error_log("Erreur validation token: " . $e->getMessage());
            throw new ExceptionInvalidToken("Erreur lors de la validation du lien. Veuillez réessayer plus tard.");
        }
    }

    /**
     * Returns a boolean depending on the success of marking used the tokken
     *
     * This method tries to change the used column of the tokken in the database. It it secceed, true is returned, false otherwise.
     *
     * @param $token the token to mark used.
     *
     * @return boolean the success of marking the tokken used
     *
     */
    public static function markTokenAsUsed(string $token): bool
    {
        try {
            $db = database::getInstance();

            $stmt = $db->prepare("
                UPDATE password_resets 
                SET used = TRUE 
                WHERE token = :token
            ");

            return $stmt->execute(['token' => $token]);
        } catch (\PDOException $e) {
            error_log("Erreur marquage token: " . $e->getMessage());
            return false;
        }
    }

    /**
     *
     *
     * This method deletes all the expired tokkens depending on their expiry time.
     *
     * @return void
     *
     */
    public static function cleanupExpiredTokens(): void
    {
        try {
            $db = database::getInstance();

            $stmt = $db->prepare("
                DELETE FROM password_resets 
                WHERE expires_at < NOW() OR used = TRUE
            ");

            $stmt->execute();
        } catch (\PDOException $e) {
            error_log("Erreur nettoyage global: " . $e->getMessage());
        }
    }
}
