<?php
namespace Utilis;

use includes\database;
use includes\exception\ExceptionInvalidToken;
use includes\exception\ExceptionSpam;

class TokenService
{
    /**
     * Generate a secure random token
     */
    public static function generate(): string
    {
        return bin2hex(random_bytes(32)); // 64 hexadecimal characters
    }

    /**
     * Create a password reset token for a given email
     * Returns the generated token or false on error
     */
    public static function createPasswordResetToken(string $email): string|false
    {
        try {
            $db = database::getInstance();
            
            // Clean up old tokens for this email
            self::cleanupOldTokens($email);
            self::cleanupExpiredTokens();
            
            // Generate new token
            $token = self::generate();
            $createdAt = date('Y-m-d H:i:s');
            $expiresAt = date('Y-m-d H:i:s', strtotime('+10 minutes'));
            
            $stmt = $db->prepare("
                INSERT INTO password_resets (user_email, token, created_at, expires_at, used)
                VALUES (:email, :token, :created_at, :expires_at, FALSE)
            ");
            
            $stmt->execute([
                'email' => $email,
                'token' => $token,
                'created_at' => $createdAt,
                'expires_at' => $expiresAt
            ]);
            
            return $token;
            
        } catch (\PDOException $e) {
            error_log("Erreur création token: " . $e->getMessage());
            if (strpos($e->getMessage(), 'TOO_MANY_RESET_REQUESTS') !== false) {
                throw new ExceptionSpam("Trop de demandes de réinitialisation. Veuillez réessayer plus tard dans quelques minutes.");
                echo "Trop de demandes de réinitialisation pour: {$email}";
            } else {
                throw $e;
            }
            return false;
        }
    }

    /**
     * Verify if a token is valid (exists, not expired, not used)
     */
    public static function validateToken(string $token): array
    {
        try {
            // Sanitize the token: allow only hexadecimal characters (since generated by bin2hex)
            if (!preg_match('/^[a-f0-9]{64}$/i', $token)) {
                return false;
            }

            $db = database::getInstance();
            
            $stmt = $db->prepare("
                SELECT user_email, expires_at, used 
                FROM password_resets 
                WHERE token = :token
            ");
            
            $stmt->execute(['token' => $token]);
            $result = $stmt->fetch(\PDO::FETCH_ASSOC);
            
            if (!$result) {
                throw new ExceptionInvalidToken("Ce lien de réinitialisation est invalide ou a expiré. Veuillez faire une nouvelle demande.");
            }
            
            if ($result['used']) {
                throw new ExceptionInvalidToken("Ce lien de réinitialisation a déjà été utilisé.");
            }
            
            if (strtotime($result['expires_at']) < time()) {
                throw new ExceptionInvalidToken("Ce lien de réinitialisation a expiré.");
            }
            
            return $result;
            
        } catch (\PDOException $e) {
            error_log("Erreur validation token: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Marks a token as used
     */
    public static function markTokenAsUsed(string $token): bool
    {
        try {
            $db = database::getInstance();
            
            $stmt = $db->prepare("
                UPDATE password_resets 
                SET used = TRUE 
                WHERE token = :token
            ");
            
            return $stmt->execute(['token' => $token]);
            
        } catch (\PDOException $e) {
            error_log("Erreur marquage token: " . $e->getMessage());
            return false;
        }
    }

    /**
     * Cleans up old tokens for a given email
     */
    private static function cleanupOldTokens(string $email): void
    {
        try {
            $db = database::getInstance();
            
            $stmt = $db->prepare("
                DELETE FROM password_resets 
                WHERE user_email = :email 
                AND (expires_at < NOW() OR used = TRUE)
            ");
            
            $stmt->execute(['email' => $email]);
            
        } catch (\PDOException $e) {
            error_log("Erreur nettoyage tokens: " . $e->getMessage());
        }
    }

    /**
     * Cleans up all expired tokens (to be run periodically)
     */
    public static function cleanupExpiredTokens(): void
    {
        try {
            $db = database::getInstance();
            
            $stmt = $db->prepare("
                DELETE FROM password_resets 
                WHERE expires_at < NOW() OR used = TRUE
            ");
            
            $stmt->execute();
            
        } catch (\PDOException $e) {
            error_log("Erreur nettoyage global: " . $e->getMessage());
        }
    }
}